host: localhost:3000
sync_pattern: "*.{csv,bef,json,xml}"
single_tenant: <%= ENV['SINGLE_TENANT'] %>
db_per_branch: false
use_demo_data: false

sidekiq_web: false

twilio_enabled: true
twilio_sid: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
twilio_auth_token: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
twilio_phone_number: "+4401234456789"
