host: localhost:3000
sync_pattern: "*.{csv,bef,json,xml}"
single_tenant: <%= ENV['SINGLE_TENANT'] %>
db_per_branch: false
use_demo_data: false

twilio:
  enabled: true
  sid: ACxxxxxx
  auth_token: xxxxxxx
  phone_number: "+441202286349"
