module Importer
  # CdxVietnam override, process a message generated by device message processor,
  # creates the associated messages in the DB with their samples, and indexes them
  class SingleMessageProcessor
    def process
      if XpertResults::VietnamImporter.valid_gene_xpert_result_and_sample?(@parent.device, @parsed_message)
        XpertResults::VietnamImporter.link_xpert_result(@parsed_message, @parent.device)
      else
        process_automatic_message
      end
    end
  end
end
