<%
  require 'config'
  branch = `git rev-parse --abbrev-ref HEAD`.strip rescue nil
  use_single_db = !Settings.db_per_branch || !branch || branch == 'master'
  branch_spec = (use_single_db ? "" : "_#{branch}").underscore.gsub(/[\.\/\-]/, '_')
%>

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  host: <%= ENV["MYSQL_HOST"] %>
  username: <%= ENV["MYSQL_USERNAME"] || "root" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "" %>

development:
  <<: *default
  database: cdp_development<%= branch_spec %>
  reconnect: true

test: &test
  <<: *default
  database: cdp_test<%= branch_spec %>

production:
  <<: *default
  database: cdp
  reconnect: true

cucumber:
  <<: *test
