host: localhost:3000
sync_pattern: "*.{csv,bef,json,xml}"
google_client_id:
google_client_secret:
google_maps_api_key:
single_tenant: <%= ENV['SINGLE_TENANT'] %>
db_per_branch: false
use_demo_data: false

# for the eTB/VTM scraper program
etb_username: <%= ENV['ETB_USERNAME'] %>
etb_password: <%= ENV['ETB_PASSWORD'] %>
etb_endpoint: <%= ENV['ETB_ENDPOINT'] %>

vtm_username: <%= ENV['VTM_USERNAME'] %>
vtm_password: <%= ENV['VTM_PASSWORD'] %>
vtm_endpoint: <%= ENV['VTM_ENDPOINT'] %>

twilio:
  enabled: false
  sid: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  auth_token: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
  phone_number: "+4401234456789"
