source 'https://rubygems.org'

# Declare your gem's dependencies in cdx_core.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'responders', '~> 2.0'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'haml-rails'
gem 'react-rails', '~> 1.3.2'
gem 'react-rails-img'
gem 'devise', '~> 3.5.5'
gem 'devise_security_extension', git: 'https://github.com/phatworx/devise_security_extension'
gem 'devise_invitable'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'paranoia'
gem 'paperclip', '~> 4.3.6'
gem 'barby'
gem 'chunky_png'
gem 'cdx', path: '../'
gem 'cdx-api-elasticsearch', path: '../'
gem 'cdx-sync-server', git: 'https://github.com/instedd/cdx-sync-server.git', branch: 'master'
gem 'geojson_import', git: 'https://github.com/instedd/geojson_import', branch: 'master'
gem 'location_service', git: 'https://github.com/instedd/ruby-location_service.git', branch: 'master'
gem 'view_components', git: 'https://github.com/manastech/rails-view_components.git', branch: 'master'
gem 'guid'
gem 'oj'
gem 'encryptor'
gem 'base58'
gem 'nuntium_api', '~> 0.21'
gem 'config'
gem 'decent_exposure', '2.3.2'
gem 'gon'
gem 'rubyzip', '>= 1.0.0'
gem 'jbuilder', '~> 1.2'
gem 'bettertabs'
gem 'csv_builder'
gem 'coffee-rails', '4.0.1'
gem 'kaminari'
gem 'therubyracer'
gem 'dotiw'
gem 'rchardet'
gem 'sidekiq', '3.5.0'
gem 'sinatra'
gem 'sidekiq-cron', '~> 0.3.1'

group :development do
  gem 'letter_opener'
  gem 'letter_opener_web'
  gem 'web-console', '~> 2.0'
  gem 'capistrano', '~> 3.1.0', require: false
  gem 'capistrano-rails', '~> 1.1', require: false
  gem 'capistrano-bundler', '~> 1.1', require: false
  gem 'capistrano-rvm', '~> 0.1', require: false
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'pry-clipboard'
  gem 'rspec-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'machinist', '~> 1.0'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'capybara-mechanize'
  gem 'shoulda'
  gem 'timecop'
  gem 'poltergeist'
  gem 'capybara-screenshot'
  gem 'webmock', '1.21.0', require: false
  gem 'site_prism'
end
